# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  	config.omnibus.chef_version = :latest
  	config.vm.box = "ubuntu/trusty32"

	config.vm.provision :shell, :inline => "sudo apt-get update -y"

	config.vm.define :verdmell1 do |verdmell|
  		verdmell.vm.network :private_network, ip: "44.44.44.10"

		verdmell.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = ["cookbooks","cookbooks/verdmell/berks-cookbooks"]
			chef.add_recipe "git"
			chef.add_recipe "golang"
			chef.add_recipe "verdmell"
		end
	end
end
