/*
Sample system management

The package 'sample' is used by verdmell to manage the samples generated by monitoring checks

-SampleEngine
-CheckSamples
*/
package sample

 import (
   "time"
   "verdmell/utils"
 )

//#
//#
//# CheckResult struct:
//# CheckResult defines a map to store the maps
type CheckSample struct{
  Check string `json:"check"`
	Exit int `json:"exit"`
  Output string `json:"output"`
  SampleTime time.Time `json:"sampletime"`
  ExpirationTime time.Duration `json:"expirationtime"`
  ElapsedTime time.Duration `json:"elapsedtime"`
  Timestamp int64 `json:"timestamp"`
}

//#
//# Getters/Setters methods for CheckSample object
//#---------------------------------------------------------------------

//
//# SetCheck: method sets the Name value for the CheckObject object sample
func (s *CheckSample) SetCheck(c string){
  	s.Check = c
}
//# SetExit: method sets the value for the CheckObject object sample
func (s *CheckSample) SetExit(e int){
  s.Exit = e
}
//# SetOutput: method sets the value for the CheckObject object sample
func (s *CheckSample) SetOutput(o string){
  s.Output = o
}
//
//# SetExpirationTime: method sets the value for the CheckObject object sample
func (s *CheckSample) SetExpirationTime(d time.Duration){
  s.ExpirationTime = d
}
//
//# SetElapsedTime: method sets the value for the CheckObject object sample
func (s *CheckSample) SetElapsedTime(d time.Duration){
  s.ElapsedTime = d
}
//
//# SetSampletime: method sets the value for the CheckObject object sample
func (s *CheckSample) SetSampletime(t time.Time){
  s.SampleTime = t
}
//
//# SetTimestamp: method sets the value for the CheckObject object sample
func (s *CheckSample) SetTimestamp(t int64){
  s.Timestamp = t
}
//
//# GetCheck: method sets the Name value for the CheckObject object sample
func (s *CheckSample) GetCheck() string{
    return s.Check
}
//
//# GetExit: method sets the value for the exit object sample
func (s *CheckSample) GetExit() int{
  return s.Exit
}
//
//# GetOutput: method sets the value for the output object sample
func (s *CheckSample) GetOutput() string {
  return s.Output
}
//
//# GetExpirationTime: method sets the value for the CheckObject object sample
func (s *CheckSample) GetExpirationTime() time.Duration {
  return s.ExpirationTime
}
//
//# GetElapsedTime: method sets the value for the CheckObject object sample
func (s *CheckSample) GetElapsedTime() time.Duration {
  return s.ElapsedTime
}
//
//# GetSampletime: method sets the value for the CheckObject object sample
func (s *CheckSample) GetSampletime() time.Time {
  return s.SampleTime
}
//
//# GetTimestamp: method sets the value for the CheckObject object sample
func (s *CheckSample) GetTimestamp() int64 {
  return s.Timestamp
}

//
//# String: method converts a sample to string
func (s *CheckSample) String() string {
  if err, str := utils.ObjectToJsonString(s); err != nil{
    return err.Error()
  } else{
    return str
  }
}
//#######################################################################################################