/*
Sample system management

The package 'sample' is used by verdmell to manage the samples generated by monitoring checks

-SampleSystem
-CheckSamples
*/
package sample

 import (
   "time"
   "strconv"
 )

//#
//#
//# CheckResult struct:
//# CheckResult defines a map to store the maps
type CheckSample struct{
  check string
	exit int
  output string
  expirationTime time.Duration
  elapsedTime time.Duration
  sampletime time.Time
}

//#
//# Getters/Setters methods for Checks object
//#---------------------------------------------------------------------

//
//# SetCheck: method sets the Name value for the CheckObject object sample
func (s *CheckSample) SetCheck(c string){
  	s.check = c
}
//# SetExit: method sets the value for the CheckObject object sample
func (s *CheckSample) SetExit(e int){
  s.exit = e
}
//# SetOutput: method sets the value for the CheckObject object sample
func (s *CheckSample) SetOutput(o string){
  s.output = o
}
//
//# SetExpirationTime: method sets the value for the CheckObject object sample
func (s *CheckSample) SetExpirationTime(d time.Duration){
  s.expirationTime = d
}
//
//# SetElapsedTime: method sets the value for the CheckObject object sample
func (s *CheckSample) SetElapsedTime(d time.Duration){
  s.elapsedTime = d
}
//
//# SetSampletime: method sets the value for the CheckObject object sample
func (s *CheckSample) SetSampletime(t time.Time){
  s.sampletime = t
}
//
//# GetCheck: method sets the Name value for the CheckObject object sample
func (s *CheckSample) GetCheck() string{
    return s.check
}
//
//# GetExit: method sets the value for the exit object sample
func (s *CheckSample) GetExit() int{
  return s.exit
}
//
//# GetOutput: method sets the value for the output object sample
func (s *CheckSample) GetOutput() string {
  return s.output
}
//
//# GetExpirationTime: method sets the value for the CheckObject object sample
func (s *CheckSample) GetExpirationTime() time.Duration {
  return s.expirationTime
}
//
//# GetElapsedTime: method sets the value for the CheckObject object sample
func (s *CheckSample) GetElapsedTime() time.Duration {
  return s.elapsedTime
}
//
//# GetSampletime: method sets the value for the CheckObject object sample
func (s *CheckSample) GetSampletime() time.Time {
  return s.sampletime
}

//
//# String: method converts a sample to string
func (s *CheckSample) String() string {
  str := "{"
  str += "check: '"+s.GetCheck()+"',"
  exit := s.GetExit() 
  str += "exit: "+strconv.Itoa(exit)+","
  str += "output: '"+s.GetOutput()+"',"
  sampletime := s.GetSampletime()
  str += "sampletime: '"+sampletime.String()+"',"
  elapsedtime := s.GetElapsedTime()
  str += "elapsedtime: "+elapsedtime.String()+","
  e := s.GetExpirationTime()
  str += "expirationtime: '"+e.String()+"'"
  str += "}"
  
  return str
}
//#######################################################################################################